# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20230210_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
